### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by i3laze** [JustAMan/pyWinClobber#11]
Утилита потрясающая!  Очистила **13** Гб на Win7x64 с материнской платой NVidia!
Для офисного компьютера с 64 Гб SSD это было волшебно.

А вот на двух других Win7x64 (развернутых из одного образа) работать отказывается. v1.0.3:

> c:\DriverStore Cleaner>driver_cleanup.exe
> Reading all OEM drivers...
> Traceback (most recent call last):
>   File "<string>", line 303, in <module>
>   File "<string>", line 202, in main
>   File "<string>", line 142, in getAllDrivers
>   File "<string>", line 71, in parseLine
> ValueError: need more than 1 value to unpack

Текущая Python-версия скрипта (master) выдаёт ту же ошибку.
Кстати, Python 3.6 ругается на синтаксис скрипта. Пришлось ставить 2.7.

UPD:
Ага.. print self.driverDateAndVersion  говорит, что есть хитрый драйвер без версии:

> 06/23/2010 5.5.0.85
> 06/23/2010 5.5.0.85
> 
> 07/20/2014 1.2.1.0
> 07/20/2014 1.2.1.0
> 
> **05/13/2015**

**Comment by i3laze** [comment]
Пожаловался [разработчику](http://www.devline.ru/forum/index.php?showtopic=4636), который подложил мне такой драйвер)
Сделал pull request.

**Comment by JustAMan** [comment]
Офигенный подход! :)

Когда я это писал - 3.х питона в принципе было мало, да и у большинства людей на машине с Windows его и сейчас нет, так что качают .exe файлы и пускают...

Что касается pull request'a - предложил способ, на мой взгляд, более элегантной обработки этой ситуации.
